### PR TITLE
build: update all non-major dependencies

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by devversion** [comment]
is there no package.json change?

**Comment by josephperrott** [comment]
Correct no package.json change. All of the changes are minor/patch updates with us having range matches in our package.json file.

**Comment by devversion** [comment]
Ahh so it's actually lock file maintenance,

**Review by devversion — APPROVED** [review]

**Comment by josephperrott** [comment]
Yeah, for whatever reason renovate didn't note it as such.  Seems like its lockfile maintenance but only for the non-major depdendencies.

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit f89362d698858f9674463e48fde514b097a15838.

**Pull request closed without merging**
