### PR TITLE
feat(bazel): support browsers for m1 platform

### PR DESCRIPTION
**Pull request by devversion**
Work in progress. Blocked on `rules_webtesting` not shipping darwin ARM64 binaries

### CODE REVIEW

**Comment by devversion** [comment]
@josephperrott we could already land this in theory. It just updates Chromium, and the m1 binaries are just not usable due to the rules_webtesting issue I mentioned to you

**Comment by josephperrott** [comment]
We can land it now if you would like, or we can wait until we are able to get the `rules_webtesting` changes sorted out first.

**Comment by devversion** [comment]
I'm happy landing this now. Marking as ready for review.

**Review by josephperrott — APPROVED** [review]
LGTM

**Pull request merged**
