### PR TITLE
build(shared-docs):  remove xterm dependency

### PR DESCRIPTION
**Pull request by JeanMeche**
`xterm` was the previous location of the same package.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by alan-agius4** [comment]
@JeanMeche please rebase.

**Review by alan-agius4 — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit ba8a5f8089795179c257dc94f2d4e823f9307156.

**Pull request closed without merging**
