### PR TITLE
feat: add cookie consent gtag event

### PR DESCRIPTION
**Pull request by bencodezen**
This PR adds the code to grant permission for cookies.

The other half of this PR is https://github.com/angular/angular/pull/54574

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
Please do not merge this PR yet, there might be a bug here, see https://github.com/angular/angular/pull/54574#pullrequestreview-1899129041.

**Comment by bencodezen** [comment]
Review has finished on https://github.com/angular/angular/pull/54574#pullrequestreview-1899129041, we should be good to go now 👍

**Comment by AndrewKushnir** [comment]
@bencodezen quick question (from https://github.com/angular/angular/pull/54574): it looks like an update happens in the accept action, which would work for the first time a user clicks the button, but after a page refresh, it looks like it would not be called again, so we end up in the "denied" state. Is that correct?

**Comment by bencodezen** [comment]
> @bencodezen quick question (from [angular/angular#54574](https://github.com/angular/angular/pull/54574)): it looks like an update happens in the accept action, which would work for the first time a user clicks the button, but after a page refresh, it looks like it would not be called again, so we end up in the "denied" state. Is that correct?
> 
> (removed the "merge" label for now, please re-add once this question is resolved)

@AndrewKushnir I can't believe I missed that. 🤦‍♂️ Yes you are absolutely correct. I've updated the code so that it checks for the localStorage state before setting the denied state. 

In addition, I've gone ahead and refactored the code to centralize the functionality which should make maintenance easier in the future. Appreciate your review on this! 🙇‍♂️

**Comment by bencodezen** [comment]
@josephperrott It looks like we're good on this! Just need your review and approval

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit 74707b165e4b6eca0b033c37191280b12539a26f.

**Pull request closed without merging**
